{
 "title": "F1Race",
 "time": { "from": "2023-03-17T21:39:50.000Z", "to": "2023-03-17T21:47:02.000Z" },
 "templating": {
  "list": [
   {
    "name": "Drivers",
    "label": "driver",
    "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> group(columns: [\"driver\"])\r\n  |> distinct(column: \"driver\")\r\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Standing",
   "type": "table",
   "gridPos": { "h": 22, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "gapDataHumanReadable = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gapToLeader\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GapToLeaderHumanReadable\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n\r\ngapData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gapToLeader\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GapToLeader\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n  \r\nintervalData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"intervalToPositionAhead\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IntervalToPositionAhead\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n\r\nlastLapData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n\r\nnumberLapsData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numberOfLaps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"NumberOfLaps\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\", \"_time\"]) \r\n\r\nintermediateJoinData1 = join(\r\n    tables: {gapHumanReadable:gapDataHumanReadable, interval:intervalData},\r\n    on: [\"driver\"],\r\n)\r\n\r\n  \r\nintermediateJoinData2 = join(\r\n    tables: {intermediateJoin1:intermediateJoinData1, numberLaps:numberLapsData},\r\n    on: [\"driver\"],\r\n)\r\n  \r\nintermediateJoinData3 = join(\r\n    tables: {intermediateJoin1:intermediateJoinData2, gap:gapData},\r\n    on: [\"driver\"],\r\n)\r\n\r\njoin(\r\n    tables: {intermediateJoin:intermediateJoinData3, lastLap:lastLapData},\r\n    on: [\"driver\"],\r\n) |> sort(columns: [\"_time\"], desc: false)  \r\n  |> sort(columns: [\"_value_gap\"], desc: false)\r\n  |> sort(columns: [\"_value_intermediateJoin1\"], desc: true)\r\n  |> fill(column: \"position\", value: 1.0)\r\n  |> cumulativeSum(columns: [\"position\"])\r\n  |> map(fn: (r) => ({ r with interval: r._value_interval * 1000.0 }))\r\n  |> map(fn: (r) => ({ r with lastLap: r._value * 1000.0 }))"
    }
   ]
  },
  {
   "title": "Lap time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: m:ss:SSS" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)\r\n  |> map(fn: (r) => ({r with lastLap: r._value * 1000.0}))\r\n  |> keep(columns: [\"driver\", \"lastLap\", \"_time\"])\r\n  "
    }
   ]
  },
  {
   "title": "Race control messages",
   "type": "logs",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raceControlMessage\")"
    }
   ]
  },
  {
   "title": "Last top speed (speed trap)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"speedTrap\")\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)"
    }
   ]
  },
  {
   "title": "Gap To Leader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gapToLeader\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GapToLeader\")\r\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)"
    }
   ]
  },
  {
   "title": "Weather data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weatherData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AirTemp\"  or r[\"_field\"] == \"TrackTemp\" or r[\"_field\"] == \"WindSpeed\" or r[\"_field\"] == \"Rainfall\")"
    }
   ]
  }
 ]
}